blank_issues_enabled: fasle
contact_links:
  - name: Ask a question or get support
    url: https://github.com/WeBankFinTech/Exchangis/discussions
    about: Ask a question or request support for using Exchangis