server:
  port: 9321
spring:
  application:
    name: exchangis-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:3306/eureka/
  instance:
    metadata-map:
      test: wedatasphere

management:
  endpoints:
    web:
      exposure:
        include: refresh,info
logging:
  config: classpath:log4j2.xml
