

server:
  port: ${server.port}
  tomcat:
    basedir: ${data.path}/tomcat/executor

jasypt:
  encryptor:
    password: bdp

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 4
    lease-expiration-duration-in-seconds: 12
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL}
    fetch-registry: true
    registry-fetch-interval-seconds: 8

auth:
  token:
    api: ENC(doiaIecpZ6QpeVvqcayuWuuWC1C5Nf1V)
