-- 插入 job_param_config 记录
INSERT INTO `exchangis_job_param_config`(config_key, config_name, config_direction, type, ui_type, ui_field, ui_label, unit, required, value_type, value_range, default_value, validate_type, validate_range, is_hidden, is_advanced, level, treename, sort, description, status) VALUES ('exchangis.job.ds.params.hive.transform_type', '传输方式', 'SOURCE', 'HIVE', 'OPTION', 'transform', '传输方式', NULL, 1, 'ARRAY', '[\"Record\", \"二进制\"]', 'Record', '', '', 0, 0, 1, '', 1, '', 1);

INSERT INTO `exchangis_job_param_config`(config_key, config_name, config_direction, type, ui_type, ui_field, ui_label, unit, required, value_type, value_range, default_value, validate_type, validate_range, is_hidden, is_advanced, level, treename, sort, description, status) VALUES ('exchangis.datax.setting.speed.channel', '并发数', NULL, 'DATAX', 'INPUT', 'channel', '并发数', NULL, 0, 'NUMBER', '1', '1', '', '', 0, 0, 1, '', 1, '', 1);
INSERT INTO `exchangis_job_param_config`(config_key, config_name, config_direction, type, ui_type, ui_field, ui_label, unit, required, value_type, value_range, default_value, validate_type, validate_range, is_hidden, is_advanced, level, treename, sort, description, status) VALUES ('exchangis.datax.setting.speed.byte', '传输速率', NULL, 'DATAX', 'INPUT', 'channel', '传输速率', 'MB/s', 0, 'NUMBER', '', '', '', '', 0, 0, 1, '', 1, '', 1);
INSERT INTO `exchangis_job_param_config`(config_key, config_name, config_direction, type, ui_type, ui_field, ui_label, unit, required, value_type, value_range, default_value, validate_type, validate_range, is_hidden, is_advanced, level, treename, sort, description, status) VALUES ('exchangis.datax.setting.errorlimit.record', '脏数据最大记录数', NULL, 'DATAX', 'INPUT', 'errorlimit_record', '脏数据最大记录数', NULL, 0, 'NUMBER', '', '', '', '', 0, 0, 1, '', 1, '', 1);
INSERT INTO `exchangis_job_param_config`(config_key, config_name, config_direction, type, ui_type, ui_field, ui_label, unit, required, value_type, value_range, default_value, validate_type, validate_range, is_hidden, is_advanced, level, treename, sort, description, status) VALUES ('exchangis.datax.setting.errorlimit.percentage', '脏数据占比阈值', NULL, 'DATAX', 'INPUT', 'errorlimit_percentage', '脏数据占比阈值', NULL, 0, 'DOUBLE', '', '', '', '', 0, 0, 1, '', 1, '', 1);


-- 插入 job_info 数据
INSERT INTO exchangis_v3.exchangis_job_info (job_name,job_desc,engine_type,alarm_user,alarm_level,content,label_map,create_time,modify_time,create_user,modify_user,to_proxy_user,exec_nodes,last_launch_time,project_id,parent_id) VALUES
('test_batch_job','test_batch_job_desc','DATAX','gujian',1,'[{"subJobName":"job0001","dataSources":{"source_id":"HIVE.10001.test_db.test_table","sink_id":"MYSQL.10002.mask_db.mask_table"},"params":{"sources":[{"config_key":"exchangis.job.ds.params.hive.transform_type","config_name":"传输方式","config_value":"二进制","sort":1},{"config_key":"exchangis.job.ds.params.hive.partitioned_by","config_name":"分区信息","config_value":"2021-07-30","sort":2},{"config_key":"exchangis.job.ds.params.hive.empty_string","config_name":"空值字符","config_value":"","sort":3}],"sinks":[{"config_key":"exchangis.job.ds.params.mysql.write_type","config_name":"写入方式","config_value":"insert","sort":1},{"config_key":"exchangis.job.ds.params.mysql.batch_size","config_name":"批量大小","config_value":1000,"sort":2}]},"transforms":{"type":"MAPPING","mapping":[{"source_field_name":"name","source_field_type":"VARCHAR","sink_field_name":"c_name","sink_field_type":"VARCHAR"},{"source_field_name":"year","source_field_type":"VARCHAR","sink_field_name":"d_year","sink_field_type":"VARCHAR"}]},"settings":[{"config_key":"exchangis.datax.setting.speed.byte","config_name":"传输速率","config_value":102400,"sort":1},{"config_key":"exchangis.datax.setting.errorlimit.record","config_name":"脏数据最大记录数","config_value":10000,"sort":2},{"config_key":"exchangis.datax.setting.errorlimit.percentage","config_name":"脏数据占比阈值","config_value":100,"sort":3}]},{"subJobName":"job0002","dataSources":{"source_id":"HIVE.10001.superman2_db.funny2_table","sink_id":"MYSQL.10002.ducky2_db.chicken2_table"},"params":{"sources":[{"config_key":"exchangis.job.ds.params.hive.transform_type","config_name":"传输方式","config_value":"二进制","sort":1},{"config_key":"exchangis.job.ds.params.hive.partitioned_by","config_name":"分区信息","config_value":"2021-07-30","sort":2},{"config_key":"exchangis.job.ds.params.hive.empty_string","config_name":"空值字符","config_value":"","sort":3}],"sinks":[{"config_key":"exchangis.job.ds.params.mysql.write_type","config_name":"写入方式","config_value":"insert","sort":1},{"config_key":"exchangis.job.ds.params.mysql.batch_size","config_name":"批量大小","config_value":1000,"sort":2}]},"transforms":{"type":"MAPPING","mapping":[{"source_field_name":"mid","source_field_type":"VARCHAR","sink_field_name":"c_mid","sink_field_type":"VARCHAR"},{"source_field_name":"maxcount","source_field_type":"INT","sink_field_name":"c_maxcount","sink_field_type":"INT"}]},"settings":[{"config_key":"exchangis.datax.setting.speed.byte","config_name":"传输速率","config_value":102400,"sort":1},{"config_key":"exchangis.datax.setting.errorlimit.record","config_name":"脏数据最大记录数","config_value":100,"sort":2}]}]','dev','2021-08-01 17:00:00','2021-08-01 17:00:00','gujian','gujian','hdfs','127.0.0.1','2021-08-01 17:00:00',1,0),
('test_stream_job','test_stream_job_desc','DATAX','gujian',1,'[{"subJobName":"streamjob0001","dataSources":{"source_id":"HIVE.10001.test_db.test_table","sink_id":"MYSQL.10002.mask_db.mask_table"},"params":{},"transforms":{"type":"SQL","sql":"select * from aaa"},"settings":[{"config_key":"exchangis.datax.setting.speed.byte","config_name":"传输速率","config_value":102400,"sort":1},{"config_key":"exchangis.datax.setting.errorlimit.record","config_name":"脏数据最大记录数","config_value":100,"sort":2}]},{"subJobName":"streamjob0002","dataSources":{"source_id":"HIVE.10001.test_db.test_table","sink_id":"MYSQL.10002.mask_db.mask_table"},"params":{},"transforms":{"type":"SQL","sql":"insert into xxx"},"settings":[{"config_key":"exchangis.datax.setting.speed.byte","config_name":"传输速率","config_value":102400,"sort":1},{"config_key":"exchangis.datax.setting.errorlimit.record","config_name":"脏数据最大记录数","config_value":10000,"sort":2},{"config_key":"exchangis.datax.setting.errorlimit.percentage","config_name":"脏数据占比阈值","config_value":100,"sort":3}]}]','dev','2021-08-01 17:00:00','2021-08-01 17:00:00','gujian','gujian','hdfs','127.0.0.1','2021-08-01 17:00:00',1,0);