name: Dead Link Check

on: [push, pull_request]

jobs:
  dead-links-check:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: (github.repository == 'WeBankFinTech/Exchangis')
    steps:
      - uses: actions/checkout@v3
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'no'
          use-verbose-mode: 'yes'
          folder-path: '../'
          config-file: '.github/workflows/dlc.json'
